import Head from 'next/head';
import { useEffect, useState } from 'react';
import { gql, useQuery } from '@apollo/client';
import CarCard from '@/components/CarCard';

export default function Home() {
  const [price, setPrice] = useState('all');

  const { loading, error, data } = useQuery(gql`
    query MyQuery {
      carDetails(where: {
        ${price === 'moreThan4' ? 'price_gt: 400000' : ''}
        ${price === 'lessThan4' ? 'price_lt: 400000' : ''}
        ${price === 'all' ? 'price_gt: 0' : ''}
      }) {
        id
        description
        gallery {
          url
        }
        nameOfTheCar
        price
        condition
      }
    }
  `);

  console.log(data);

  const options = [
    { value: 'all', label: 'All' },
    { value: 'moreThan4', label: '> 400000' },
    { value: 'lessThan4', label: '< 400000' },
  ];

  const onChange = (e) => {
    setPrice(e.target.value);
    console.log(e.target.value);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div>
          <label htmlFor='price'>Filter By Price:</label>
          <select id='price' value={price} onChange={onChange}>
            {options.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
        </div>
        {loading ? (
          <p>Loading...</p>
        ) : (
          data.carDetails.map((car) => (
            <CarCard
              key={car.id}
              imageUrl={car.gallery[0].url}
              description={car.description}
              name={car.nameOfTheCar}
              price={car.price}
              condition={car.condition}
              id={car.id}
            />
          ))
        )}
      </main>
    </>
  );
}
